apiVersion: batch/v1
kind: Job
metadata:
  name: kubetui-japanese
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: init-0
          image: alpine
          command:
            - sh
            - -c
          args:
            - 'printf "ああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春春"; exit 0'
        - name: init-1
          image: alpine
          command:
            - sh
            - -c
          args:
            - "echo init-1; exit 0"
      containers:
        - name: app
          image: alpine
          command:
            - sh
            - -c
          args:
            - "echo app; exit 0"
