apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetui-simple
spec:
  selector:
    matchLabels: # or matchExpressions:
      app: kubetui-simple
  template:
    metadata:
      labels:
        app: kubetui-simple
    spec:
      initContainers:
        - name: echo
          image: alpine
          command:
            - sh
            - -c
          args:
            - "echo init-1; exit 0"

      containers:
        - name: app
          image: nginx
